barddo/api/urls.py
from django.conf.urls import patterns, url, include
from rest_framework.routers import DefaultRouter

from api.views import register_by_access_token, UserFeedViewSet, PageRetrieve, UserFriendsViewSet, FavoritesViewSet, WorksViewSet, WorkSearchViewSet, \
    CompleteWorkViewSet
from api.new_api import RemotePagesViewSet, MangaListViewSet, MangaStatusListViewSet


router = DefaultRouter()

# User actions feed
router.register(r'feed', UserFeedViewSet, base_name="user-feed")

# User friends list
router.register(r'friends', UserFriendsViewSet, base_name="user-friends")

# User favorite works
router.register(r'favorites', FavoritesViewSet, base_name="user-favorites")

router.register(r'work', CompleteWorkViewSet, base_name="work")

router.register(r'works', WorksViewSet, base_name="works")

router.register(r'search-work', WorkSearchViewSet, base_name="search-work")

# New Api URL's
router.register(r'mangas', MangaListViewSet, base_name="manga-brazil-list")
router.register(r'pages', RemotePagesViewSet, base_name="remote-pages")
router.register(r'status', MangaStatusListViewSet, base_name="mangas-status")

urlpatterns = patterns(
    '',

    url(r'^work/(?P<work_id>\d+)/page/(?P<page_number>\d+)/',
        PageRetrieve.as_view(),
        name='work_page'),

    url(r'^', include(router.urls)),

    url(r'^token/register/(?P<backend>[^/]+)/$',
        register_by_access_token,
        name='register.token'),

    url(r'', include('rest_framework.urls', namespace='rest_framework'))
)

barddo/publishing/urls.py
from django.conf.urls import patterns, url

from .views import publisher_landpage, JoinBarddoModal, CountriesAjaxView, CreateGroupModal


urlpatterns = patterns(
    '',
    url(r'publisher$', publisher_landpage, name='publishing.landpage'),
    url(r'^profile$', JoinBarddoModal.as_view()),  # TODO: temporary url, because the autodiscover doesnt work with shards.
    url(r'^profile$', CreateGroupModal.as_view()),  # TODO: temporary url, because the autodiscover doesnt work with shards.
    url(r'publisher/countries$', CountriesAjaxView.as_view(), name='publisher.countries'),

)

barddo/publishing/models.py
from django.contrib.contenttypes.generic import GenericRelation
from django.db import models
from django.db.models.fields import CharField

from accounts.models import BarddoUser
from core.models import Collection
from follow.models import Follow


__author__ = 'bruno'


class Country(models.Model):
    country_name = CharField(max_length=50, unique=True)
    country_language = CharField(max_length=50, unique=True)


class PublishingHouse(models.Model):
    name = models.CharField(max_length=40, unique=True)
    avatar = models.ImageField(upload_to='publisher_avatar/')
    info = models.TextField()
    country = models.ForeignKey(Country)
    collections = models.ForeignKey(Collection, blank=True, null=True)
    owner = models.ForeignKey(BarddoUser, related_name='publishing_group_owner')
    publishers = models.ManyToManyField(BarddoUser, blank=True, null=True, related_name='publishing_group')
    followee = GenericRelation(Follow, related_name='publishing_followee')

barddo/publishing/forms.py
from django.forms import ModelForm

from publishing.models import PublishingHouse


__author__ = 'bruno'


class PublishingGroupForm(ModelForm):
    class Meta:
        model = PublishingHouse
        exclude = ['collections', 'owner']

barddo/publishing/views.py
import json

from django.http.response import HttpResponse
from django.views.generic import View
from django.views.generic.base import TemplateResponseMixin

from core.views import ProfileAwareView, LoginRequiredMixin
from publishing.models import Country
from shards.decorators import register_shard


__author__ = 'bruno'


class PublisherLandpage(LoginRequiredMixin, ProfileAwareView):
    template_name = 'publisher_landpage.html'

    def get(self, request, *args, **kwargs):
        user = request.user
        is_barddo_publisher = user.is_barddo_publisher()
        context = {'barddo_publisher': is_barddo_publisher}
        return super(PublisherLandpage, self).get(request, **context)


publisher_landpage = PublisherLandpage.as_view()


@register_shard(name=u'join.barddo')
class JoinBarddoModal(LoginRequiredMixin, TemplateResponseMixin, View):
    template_name = 'join_barddo_modal.html'

    def post(self, *args, **kwargs):
        return super(JoinBarddoModal, self).render_to_response({})


@register_shard(name=u'create.group')
class CreateGroupModal(LoginRequiredMixin, TemplateResponseMixin, View):
    template_name = 'create_group_modal.html'

    def post(self, *args, **kwargs):
        return super(CreateGroupModal, self).render_to_response({})


class CountriesAjaxView(LoginRequiredMixin, View):
    def get(self, *args, **kwargs):
        countries = Country.objects.all()
        countries = map(lambda x: {'id': x.id, 'text': x.country_name}, countries)
        data = json.dumps(countries)
        return HttpResponse(data, content_type='application/json')

barddo/publishing/templates/create_group_modal.html
{% load i18n %}
{% load staticfiles %}

<div class="modal fade" id="createGroupModal" role="dialog" aria-labelledby="createGroupLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="createGroupLabel">{% trans "Create your own group!" %}</h4>
            </div>
            <div class="modal-body">
                <form id="publishingGroupForm" class="form-horizontal" enctype="multipart/form-data" role="form">
                    {% csrf_token %}
                    <div class="profile-picture pull-left height-auto publishing-avatar-preview">
                        <input id="id_avatar" type="file" name="avatar"/>
                    </div>
                    <div id="group-name-validation" class="margin-bottom-10 pull-left width-60 form-group has-info no-margin-left no-margin-right">
                        <span class="block input-icon input-icon-right">
                            <input class="form-control about_publisher" type="text" name="name" id="id_name" placeholder="{% trans "Group name" %}"/>
                            <i class="icon-info-sign"></i>
                        </span>
                    </div>

                    <div class="margin-bottom-10 pull-left width-60 form-group no-margin-right no-margin-left">
                        <textarea class="form-control about_publisher" name="info" id="id_info" placeholder="{% trans "We are awesome!" %}"></textarea>
                    </div>

                    <div class="clearfix"></div>

                    <div class="form-group no-margin-right no-margin-left">
                        <label for="id_country">{% trans "Country" %}:</label>
                        <input id="id_country" class="width-100 select2-offscreen" name="country" type="hidden" tabindex="-1">
                    </div>
                    <label for="id_publishers">{% trans "Publishers" %}:</label>
                    <select multiple id="id_publishers" name="publishers" data-role="tagsinput"></select>


                    <div class="checkbox">
                        <label>
                            <input name="form-field-checkbox" type="checkbox" class="ace">
                            <span class="lbl"> {% trans "I agree with the" %} <a href="#">{% trans "Terms of use" %}</a>!</span>
                        </label>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">{% trans "Close" %}</button>
                <button id="createBtn" type="button" class="btn disabled btn-primary">{% trans "Create group" %}</button>
            </div>
        </div>
    </div>
</div>
<script src="{% static "barddo/js/pages/publishing.group.create.js" %}"></script>
<script type="text/javascript">

    var $createBtn = $("#createBtn");
    $("input[type=checkbox]").on("click", function () {
        if ($createBtn.hasClass("disabled")) {
            $createBtn.removeClass("disabled");
        } else {
            $createBtn.addClass("disabled");
        }
    });

    $.getJSON("{% url "publisher.countries" %}", function (countries) {
        $('#id_country').select2({
            allowClear: true,
            placeholder: "{% trans "Select a country" %}",
            data: countries
        });
    });


    $('#id_publishers').tagsinput({
        itemValue: 'id',
        itemText: 'username',
        freeInput: false,
        typeahead: {
            source: function (search) {
                return $.getJSON("{% url "accounts.usernames" %}", {'q': search});
            }
        }
    });

    var $form = $('#publishingGroupForm');
    var $file_input = $form.find('input[type=file]');

    $file_input.ace_file_input({
        style: 'well',
        btn_choose: '{% trans "Choose an Avatar" %}',
        btn_change: null,
        droppable: false,
        thumbnail: 'large',
        before_change: function (files) {
            var file = files[0];
            var type = $.trim(file.type);
            if ((type.length > 0 && !(/^image\/(jpe?g|png|gif)$/i).test(type)) || (type.length == 0 && !(/\.(jpe?g|png|gif)$/i).test(file.name))) {
                gritterError('{% trans 'Error'%}', '{% trans 'Please select an image file!' %}', true);
                return false;
            }
            if (file.size > 512000) {
                gritterError('{% trans 'error' %}', '{% trans 'File size should not exceed 500Kb!' %}');
                return false;
            }
            return true;
        }
    });

    $createBtn.on("click", function () {
        var options = {
            success: Dajax.process,  // post-submit callback
            url: "/dajaxice/publishing.register_publishing_group/",         // override for form's 'action' attribute
            type: "post"
        };

        $('#publishingGroupForm').ajaxSubmit(options);
    });

    function callback_create_group_error(id, error) {
        if (id == '#id_country') {
            id = '#' + $(id).prev().attr('id');
        }
        $(id).closest('.form-group').addClass('has-error');
        error_tooltip(id, error, 3000, 'bottom');
    }

</script>

barddo/publishing/templates/join_barddo_modal.html
{% load i18n %}

<div class="modal fade" id="joinBarddoModal" tabindex="-1" role="dialog" aria-labelledby="joinBarddoLabel" aria-hidden="true">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="joinBarddoLabel">{% trans "Join the barddo team!" %}</h4>
            </div>
            <div class="modal-body">
                <h3>{% trans "Please read our" %} <a target="_blank" href="{% url "core.terms" %}">{% trans "Terms of use" %}</a>!</h3>

                <form class="form-horizontal" role="form">
                    <div class="checkbox">
                        <label>
                            <input name="form-field-checkbox" type="checkbox" class="ace">
                            <span class="lbl"> {% trans "I agree with the terms of use!" %}</span>
                        </label>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">{% trans "Close" %}</button>
                <button id="joinButton" type="button" class="btn disabled btn-primary">{% trans "Join" %}</button>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $("input[type=checkbox]").on("click", function () {
        var $joinButton = $("#joinButton");
        if ($joinButton.hasClass("disabled")) {
            $joinButton.removeClass("disabled");
        } else {
            $joinButton.addClass("disabled");
        }
    });

    $("#joinButton").on("click", function () {
        Dajaxice.publishing.register_user_in_barddo(Dajax.process, {})
    });


    function join_barddo_callback(message) {
        gritterError("", message, true);
    }
</script>

barddo/publishing/templates/publisher_landpage.html
{% extends 'main_template.html' %}
{% load staticfiles %}
{% load dajaxice_templatetags %}
{% load i18n %}
{% load compress %}


{% block header %}
    {% compress css %}
        <link rel="stylesheet" href="{% static "bootstrap-tagsinput/css/bootstrap-tagsinput.css" %}"/>
        <link rel="stylesheet" href="{% static "custom-modal/css/style.css" %}"/>
        <link rel="stylesheet" href="{% static "css/select2.css" %}"/>
        <link rel="stylesheet" href="{% static "barddo/css/barddo.publisher.css" %}"/>
    {% endcompress %}
{% endblock %}

{% block breadcrumbs %}
    <ul class="breadcrumb">
        <li>
            <i class="icon-home home-icon"></i>
            <a href="{% url "core.index" %}">{% trans "Home" %}</a>
        </li>
        <li class="active">{% trans "Publisher" %}</li>
    </ul>
{% endblock %}

{% block content %}
    <div class="page-content no-padding">
        <div class="features block">
            <div class="container">
                <div class="row">
                    <div class="col-md-5 col-xs-12 sketch">
                        <img src="{% static "barddo/img/sketch.png" %}">
                    </div>
                    <div class="col-md-7 col-xs-12">
                        <div class="page-title text-center">
                            <h3>{% trans "Barddo for Artists" %}!</h3>
                            <button id="joinBarddoButton"
                                    class="{% if barddo_publisher %} disabled {% endif %}btn btn-orange btn-lg">
                                {% if not barddo_publisher %}{% trans "I want to publish in Barddo!" %}{% else %}
                                    {% trans "You are a Barddo publisher!" %}{% endif %}
                            </button>
                            <p class="text-left">
                                {% blocktrans %}
                                    Welcome!
                                    Are you an independent artist that wants to share your creations with the world? You're in the right place!
                                    Barddo will help you to achieve all of your goals as an artist.
                                {% endblocktrans %}
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="shots block">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6">
                        <div class="col-md-8">
                            <div class="shotcontent second">
                                <h3>{% trans "Mobility" %}</h3>

                                <p class="shot-para">
                                    {% blocktrans %}
                                        With barddo you publish once and readers read anywhere, either on the computer or on their mobile devices.
                                    {% endblocktrans %}
                                </p>
                                <hr>

                                <div class="row">
                                    <div class="col-md-6 col-xs-6">
                                        <div class="shot-content-body">
                                            <h4><i class="icon-mobile-phone tblue"></i> {% trans "Mobile" %}</h4>

                                            <p>
                                                {% blocktrans %}
                                                    Barddo's mobile app are ready to be used in today's most famous platforms
                                                    such as IOS, Android, Windows Phone and FirefoxOS.
                                                {% endblocktrans %}
                                            </p>
                                        </div>
                                    </div>
                                    <div class="col-md-6 col-xs-6">
                                        <div class="shot-content-body">
                                            <h4><i class="icon-desktop tblue"></i> {% trans "Web" %}</h4>

                                            <p>
                                                {% blocktrans %}
                                                    The website will continue to receive improvements so the readers can have the best experience buying and
                                                    reading your comics.
                                                {% endblocktrans %}
                                            </p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div style="height: 100px;" class="hidden-xs"></div>
                            <div class="screenshot">
                                <img src="{% static "img/phone-barddo-04.png" %}" alt="image"
                                     class="img-responsive"/>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="col-md-8">
                            <div class="shotcontent second">
                                <h3>{% trans "Monetize your comic" %}</h3>

                                <p class="shot-para">
                                    {% blocktrans %}
                                        With Barddo you can sell your comics, why not earn some money doing things that you love!
                                    {% endblocktrans %}
                                </p>
                                <hr>

                                <div class="row">
                                    <div class="col-md-6 col-xs-6">
                                        <div class="shot-content-body">
                                            <h4><i class="icon-money tblue"></i> {% trans "Price" %}</h4>

                                            <p>
                                                {% blocktrans %}
                                                    You say the price! it is important for us that the creator of the comic have the freedom to choose the worth
                                                    of their own work!
                                                {% endblocktrans %}
                                            </p>
                                        </div>
                                    </div>
                                    <div class="col-md-6 col-xs-6">
                                        <div class="shot-content-body">
                                            <h4><i class="icon-dollar tblue"></i> {% trans "Share" context "Monetize" %}</h4>

                                            <p>
                                                {% blocktrans %}
                                                    As service providers we will keep a small share from this value, it is important for us to be able to
                                                    keep the service running!
                                                {% endblocktrans %}
                                            </p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div style="height: 100px;" class="hidden-xs"></div>
                            <div class="screenshot">
                                <img src="{% static "barddo/img/cifrao.png" %}" alt="image"
                                     class="img-responsive"/>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block page_specific_javascript %}
    {% compress js %}
        <script src="{% static "bootstrap-tagsinput/js/bootstrap-tagsinput.js" %}"></script>
        <script src="{% static "ace/js/ace-elements.js" %}"></script>
        <script src="{% static "js/jquery.form.min.js" %}"></script>
        <script src="{% static "js/uncompressed/select2.js" %}"></script>
    {% endcompress %}
{% endblock %}

{% block bottom_page %}
    <script type="text/javascript">
        $(document).ready(function () {
            $("#joinBarddoButton").on("click", function () {
                Shards.join.barddo(function (shard_id, shard_data, parent) {
                    $(shard_id).remove();
                    $(parent).append(shard_data);
                    $(shard_id).modal('show');
                });
            });
        });

    </script>
{% endblock %}